name: Auto approve and merge PRs

# Trigger the workflow on pull request
on:
  pull_request

jobs:
   automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflows: "main.yml"
