name: PR for dev branch
on:
  push:
    branches:
      - "temp-dev"

jobs:
  create-pull-request-for-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: create-pull-request-for-dev
        run: gh pr create -B dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    needs: create-pull-request-for-dev
    environment: cherrypick_for_pp
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'temp-pp'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: <BOT_EMAIL>
        DRY_RUN: false
