name: PR for dev branch
on:
  push:
    branches:
      - "developer"

jobs:
  create-pull-request-for-dev:
    runs-on: ubuntu-latest
    name: create-pull-request-for-dev
    environment: create-pull-request-for-dev
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'dev'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: <BOT_EMAIL>
        DRY_RUN: false
          
  create-pull-request-for-pp:
    runs-on: ubuntu-latest
    name: create-pull-request-for-pp
    needs: create-pull-request-for-dev
    environment: create-pull-request-for-pp
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      id: cpr
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'pp'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: <BOT_EMAIL>
        DRY_RUN: false

    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

  create-pull-request-for-prod:
    runs-on: ubuntu-latest
    name: create-pull-request-for-prod
    needs: create-pull-request-for-pp
    environment: create-pull-request-for-prod
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'prod'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: <BOT_EMAIL>
        DRY_RUN: false
